{
  "swagger": "2.0",
  "info": {
    "version": "1.0.0",
    "title": "Teste Prático - Desenvolvedor WEB (DASS 2025)",
    "description": "Teste Prático - Desenvolvedor WEB (DASS 2025)"
  },
  "host": "localhost:3000",
  "basePath": "",
  "schemes": [
    "http"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/employees": {
      "get": {
        "description": "Lista todos os funcionários",
        "responses": {
          "default": {
            "description": ""
          }
        }
      },
      "post": {
        "description": "Cria um novo funcionário",
        "responses": {
          "default": {
            "description": ""
          }
        }
      }
    },
    "/employees/{id}": {
      "delete": {
        "description": "Deleta um funcionário",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "default": {
            "description": ""
          }
        }
      },
      "put": {
        "description": "Atualiza um funcionário",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "default": {
            "description": ""
          }
        }
      },
      "patch": {
        "description": "Atualiza um funcionário",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "default": {
            "description": ""
          }
        }
      },
      "get": {
        "description": "Busca um funcionário por ID (primary key)",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "default": {
            "description": ""
          }
        }
      }
    }
  }
}