services:
  premiarh-api:
    build: ../ 
    container_name:  premiarh-api
    ports:
      - "3000:3000"
    depends_on:
      - premiarh-db
    environment:
      - POSTGRES_HOST=premiarh-db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=premiarh
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=12345
      - PORT=3000
    restart: always
    networks:
      - premiarh-network

  premiarh-db:
    build: .
    container_name: premiarh-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=premiarh
    ports:
      - "5432:5432"
    restart: always
    networks:
      - premiarh-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: premiarh-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - premiarh-db
    networks:
      - premiarh-network

  premiarh-front:
    build:
      context: ../../Front
      dockerfile: Dockerfile
    container_name: premiarh-front
    command: quasar dev -H 0.0.0.0
    ports:
      - "8080:8080"
    volumes:
      - ../../Front:/app
    depends_on:
      - premiarh-api
    networks:
      - premiarh-network

networks:
  premiarh-network:
    driver: bridge
